phy = int(input("Physics:"))
che = int(input("Chemistry:"))
mat = int(input("Maths:"))

total=int(phy+mat+che)
per=float(total*100/300)

print("Total:", total)
print("Percentage:%0.2f" % per)
if per > 60:
    print("You are Pass")
    print("                 ``                                                                        ```.`")
    print("               `+/                                                                 ``.-/+o+:-.    ")
    print("             `/mo                                                          ``.-:+syhdhs/-`          ")
    print("            -hMd                                                    `..:+oyhmNNmds/-`               ")
    print("          `oNMM/                                            ``.-/oyhdmMMMMNdy+:.                    ")
    print("         .hMMMM-                                     `.-/+shdmNMMMMMMNdy+:.                         ")
    print("        :mMMMMM+                             `.-:+sydmNMMMMMMMMMNmho:.`                             ")
    print("       :NMMMMMMN:                    `.-:/oyhmmNMMMMMMMMMMMNmho:.`                                  ")
    print("      .NMMMMMMMMNy:`          `.-/oshdmNMMMMMMMMMMMMMMMmhs/-`                                       ")
    print("      hMMMMMMMMMMMMmhysooosyhdmNMMMMMMMMMMMMMMMMMMmds/-`                                            ")
    print("     .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdy+-.`                                                ")
    print("     -MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdy+-.`                                                     ")
    print("     `NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmyo:.`                                                          ")
    print("      /NMMMMMMMMMMMMMMMMMMMMMMMmho:.`                                                               ")
    print("       .yNMMMMMMMMMMMMMMMMmhs/.`                                                                    ")
    print("         ./shdmNNmmdhyo/-``                                                                         ")
    print("              `````                         ")
else:
    print("You are Fail")
    print("                                 _________ ")
    print("                               /         /.")
    print("        .-------------.       /_________/ |")
    print("       /             / |      |         | |")
    print("      /+============+\ |      | |====|  | |")
    print("      ||C:\>        || |      |         | |")
    print("      ||  computer  || |      | |====|  | |")
    print("      ||   says     || |      |   ___   | |")
    print("      ||   no!!!    || |      |  |166|  | |")
    print("      ||            ||/@@@    |   ---   | |")
    print("      \+============+/    @   |_________|./.")
    print("                         @          ..  ....'")
    print("      ..................@     __.'.'  ''")
    print("     /oooooooooooooooo//     ///")
    print("    /................//     /_/")
    print("    ------------------")
